#######################################################
################## Predownload Repos ##################
#######################################################
---
- name: "Wait for offline repository to come up if it exists"
  uri:
    url: http://reposerver/offlinerepo/repodata/repomd.xml
  register: repowebresult
  until: repowebresult.status == 200
  retries: 3
  delay: 1

- name: "Setup repo on all machines"
  yum_repository:
    baseurl: "http://reposerver/offlinerepo"
    description: "Locally hosted repo"
    gpgcheck: false
    name: rockrepo
    enabled: true

- name: "Install yum-utils on all machines"
  yum:
    name: 'yum-utils'
    enablerepo: 'rockrepo'
    disablerepo: '*'
    state: present

- name: "Disable all repos"
  shell: 'yum-config-manager --disable \*'
  
- name: "Enable rock repo!"
  shell: 'yum-config-manager --enable rockrepo'
...
